export default {
  id: "github-models",
  alias: "ghm",
  hasFree: true,
  display: {
    name: "GitHub Models",
    icon: "code",
    color: "#238636",
    textIcon: "GH",
    website: "https://github.com/marketplace/models",
    notice: { text: "Free GPT-5, o-series, DeepSeek-R1, Llama 4, Grok 3 — GitHub account only." },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://models.github.ai/inference/chat/completions",
    auth: { header: "Authorization", scheme: "raw" },
  },
  models: [
    { id: "openai/gpt-4.1", name: "GPT-4.1 (Free)" },
    { id: "openai/gpt-4o", name: "GPT-4o (Free)" },
    { id: "openai/gpt-4o-mini", name: "GPT-4o Mini (Free)" },
    { id: "openai/o1", name: "o1 (Free)" },
    { id: "openai/o3", name: "o3 (Free)" },
    { id: "openai/o4-mini", name: "o4-mini (Free)" },
    { id: "deepseek/DeepSeek-R1", name: "DeepSeek R1 (Free)" },
    { id: "meta/Llama-4-Maverick-17B-128E-Instruct", name: "Llama 4 Maverick (Free)" },
    { id: "xai/grok-3", name: "Grok 3 (Free)" },
    { id: "mistral-ai/Mistral-Medium-3", name: "Mistral Medium 3 (Free)" },
    { id: "cohere/Cohere-command-a", name: "Cohere Command A (Free)" },
    { id: "microsoft/Phi-4", name: "Phi-4 (Free)" },
    { id: "openai/text-embedding-3-large", name: "Text Embedding 3 Large (Free)" },
    { id: "openai/text-embedding-3-small", name: "Text Embedding 3 Small (Free)" },
  ],
};
