export default {
  id: "gitlawb-gmi",
  alias: "glb-gmi",
  display: {
    name: "Gitlawb Opengateway (GMI Cloud)",
    icon: "hub",
    color: "#10B981",
    textIcon: "GMI",
    website: "https://opengateway.gitlawb.com",
    notice: { text: "Free Nemotron promo ended 2026-06 — the GMI Cloud route is now pay-as-you-go credit only." },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://opengateway.gitlawb.com/v1/gmi-cloud",
  },
  models: [
    { id: "XiaomiMiMo/MiMo-V2.5-Pro", name: "MiMo-V2.5-Pro (GMI)" },
    { id: "XiaomiMiMo/MiMo-V2.5", name: "MiMo-V2.5 (GMI)" },
    { id: "openai/gpt-5.5", name: "GPT-5.5" },
    { id: "openai/gpt-5.4-pro", name: "GPT-5.4 Pro" },
    { id: "openai/gpt-5.4", name: "GPT-5.4" },
    { id: "openai/gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "openai/gpt-5.4-nano", name: "GPT-5.4 Nano" },
    { id: "openai/gpt-5.3-codex", name: "GPT-5.3 Codex" },
    { id: "openai/gpt-5.2-codex", name: "GPT-5.2 Codex" },
    { id: "openai/gpt-5.2", name: "GPT-5.2" },
    { id: "openai/gpt-5.1", name: "GPT-5.1" },
    { id: "openai/gpt-5", name: "GPT-5" },
    { id: "openai/gpt-4o", name: "GPT-4o" },
    { id: "openai/gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "anthropic/claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "anthropic/claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "anthropic/claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "anthropic/claude-opus-4.1", name: "Claude Opus 4.1" },
    { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "anthropic/claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "anthropic/claude-sonnet-4", name: "Claude Sonnet 4" },
    { id: "anthropic/claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "deepseek-ai/DeepSeek-V4-Pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-ai/DeepSeek-V4-Flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-ai/DeepSeek-R1-0528", name: "DeepSeek R1" },
    { id: "deepseek-ai/DeepSeek-V3.2", name: "DeepSeek V3.2" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro" },
    { id: "google/gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite" },
    { id: "google/gemini-3-flash-preview", name: "Gemini 3 Flash" },
    { id: "zai-org/GLM-5.1-FP8", name: "GLM-5.1" },
    { id: "zai-org/GLM-5-FP8", name: "GLM-5" },
    { id: "moonshotai/Kimi-K2.6", name: "Kimi K2.6" },
    { id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5" },
    { id: "MiniMaxAI/MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "MiniMaxAI/MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "Qwen/Qwen3.6-Max-Preview", name: "Qwen3.6 Max" },
    { id: "Qwen/Qwen3.6-Plus", name: "Qwen3.6 Plus" },
    { id: "Qwen/Qwen3.5-397B-A17B", name: "Qwen3.5 397B" },
    { id: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8", name: "Qwen3 Coder 480B" },
    { id: "nvidia/NVIDIA-Nemotron-3-Nano-Omni", name: "Nemotron 3 Nano" },
  ],
  passthroughModels: true,
};
